-- place-bid.lua
-- Atomic bid placement. Runs in Redis as a single transaction — no race
-- conditions possible. Either the bid wins the top-of-book slot or it is
-- rejected with a specific reason.
--
-- KEYS:
--   [1] auction:<auctionId>:state   (hash: status, startsAt, endsAt, minIncrement, startingPrice, highBid, highBidderId, version)
--   [2] auction:<auctionId>:bids    (sorted set: member=bidId, score=amount+timestampFraction — for history)
--
-- ARGV:
--   [1] bidId           (uuid generated by caller)
--   [2] bidderId        (user uuid)
--   [3] amount          (integer, paisa)
--   [4] nowMs           (current epoch ms — caller supplies, we don't trust server time drift)
--
-- Returns Lua table { ok, reason, prevHighBid, prevHighBidderId, newHighBid, version }
-- Encoded as JSON string for ease of parsing in Node.
local state_key = KEYS[1]
local bids_key  = KEYS[2]
local bid_id    = ARGV[1]
local bidder_id = ARGV[2]
local amount    = tonumber(ARGV[3])
local now_ms    = tonumber(ARGV[4])

if not redis.call('EXISTS', state_key) then
  return cjson.encode({ ok = false, reason = 'AUCTION_NOT_FOUND' })
end

local state = redis.call('HMGET', state_key,
  'status', 'startsAt', 'endsAt', 'minIncrement', 'startingPrice',
  'highBid', 'highBidderId', 'version')
local status        = state[1]
local starts_at     = tonumber(state[2])
local ends_at       = tonumber(state[3])
local min_increment = tonumber(state[4])
local starting      = tonumber(state[5])
local high_bid      = tonumber(state[6]) or 0
local high_bidder   = state[7]
local version       = tonumber(state[8]) or 0

-- Status gates
if status ~= 'live' then
  return cjson.encode({ ok = false, reason = 'AUCTION_NOT_LIVE', status = status })
end
if now_ms < starts_at then
  return cjson.encode({ ok = false, reason = 'AUCTION_NOT_STARTED' })
end
if now_ms >= ends_at then
  return cjson.encode({ ok = false, reason = 'AUCTION_ENDED' })
end

-- Self-outbid guard
if high_bidder == bidder_id and high_bid > 0 then
  return cjson.encode({ ok = false, reason = 'ALREADY_HIGHEST_BIDDER', highBid = high_bid })
end

-- Amount must beat current high + min_increment, or (first bid) meet starting price
local required_min
if high_bid == 0 then
  required_min = starting
else
  required_min = high_bid + min_increment
end

if amount < required_min then
  return cjson.encode({
    ok = false,
    reason = 'AMOUNT_TOO_LOW',
    requiredMin = required_min,
    currentHighBid = high_bid,
  })
end

-- Commit: bump version, replace top of book, append history
version = version + 1
redis.call('HSET', state_key,
  'highBid', amount,
  'highBidderId', bidder_id,
  'version', version,
  'lastBidAt', now_ms,
  'lastBidId', bid_id)

-- Append to sorted-set history. Score = amount * 1e13 + nowMs to keep amount primary,
-- time tiebreak. Value = bidId (caller already has userId + amount in Postgres write).
local score = amount * 10000000000000 + now_ms
redis.call('ZADD', bids_key, score, bid_id)

-- Anti-sniping extension: if less than 30s remain, push endsAt forward by 30s.
-- Caller is notified via `extendedEndsAtMs` and broadcasts to room.
local extended = false
local new_ends_at = ends_at
if ends_at - now_ms < 30000 then
  new_ends_at = now_ms + 30000
  redis.call('HSET', state_key, 'endsAt', new_ends_at)
  extended = true
end

return cjson.encode({
  ok = true,
  prevHighBid = high_bid,
  prevHighBidderId = high_bidder,
  newHighBid = amount,
  newHighBidderId = bidder_id,
  version = version,
  endsAt = new_ends_at,
  extended = extended,
})
